server:
  port: 8090
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/userdb
    # username and password properties will be injected by the vault
    #    username: test
    #    password: test
    jpa:
      hibernate:
        ddl-auto: none
  config:
    import: vault://
  application:
    name: myapp
  cloud:
    vault:
      authentication: TOKEN
      token: "0000"
      uri: http://vault:8201
      scheme: http
      host: vault
      port: 8201
      fail-fast: true
      kv:
        enabled: true
        backend: secret
        default-context: myapp
      database:
        enabled: true
        backend: database
        role: dynamic-role